name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  env_pages: ${{ vars.PAGES }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18 ]
        # node-version: [10, 12, 14, 16, 18]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm-version
        run: npm version
      # 安装依
      - name: install
        run: npm i --registry https://registry.npmmirror.com
      # 构建
      - name: build
        run: npm run build
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: yolo-lables.node${{ matrix.node-version }}
      #     path: dist
      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        #if: github.ref == 'refs/heads/main' and  env.env_pages != ''
        if: ${{ env.env_pages != '' &&  github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
